"""Add User.is_auth

Revision ID: 367b19bd951b
Revises: dede16ebc06b
Create Date: 2022-12-14 15:29:53.643470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367b19bd951b'
down_revision = 'dede16ebc06b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_auth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_auth')
    # ### end Alembic commands ###
